export * from './DetailDosen'
export * from './DetailKepegawaian'
export * from './DetailDomisili'
export * from './DetailDomisili'
export * from './DetailRekening'
export * from './DetailDokumen'
export * from './DetailKependukuan'
export * from './DetailDataLain'
